# generated by Hoe
Gem::Specification.new do |s|
  s.name = %q{feedme}
  s.version = "0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Didion"]
  s.date = %q{2009-09-11}
  s.description = %q{A simple, flexible, and extensible RSS and Atom parser for Ruby. Based on the popular SimpleRSS library, but with many nice extra features.}
  s.email = ["github@didion.net"]
  s.extra_rdoc_files = ["History.txt", "Manifest.txt", "README.txt"]
  s.files = ["History.txt", "Manifest.txt", "README.txt", "Rakefile", "lib/feedme.rb", "examples/rocketboom.rb", "examples/rocketboom.rss", "test/test_helper.rb"]
  s.homepage = %q{http://wiki.github.com/jdidion/feedme}
  s.rdoc_options = ["--main", "README.txt"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{feedme}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A simple, flexible, and extensible RSS and Atom parser for Ruby}
  s.test_files = ["test/test_helper.rb"]
end
