require 'rubygems'
require 'jeweler'

tasks = Jeweler::Tasks.new do |s|
  s.name = "feedme"
  s.authors = ["John Didion"]
  s.description = %q{A simple, flexible, and extensible RSS and Atom parser for Ruby. Based on the popular SimpleRSS library, but with many nice extra features.}
  s.email = ["code@didion.net"]
  s.extra_rdoc_files = ["History.txt", "Manifest.txt", "README.txt"]
  s.files = ["History.txt", "Manifest.txt", "README.txt", "Rakefile", 
    "lib/feedme.rb", "lib/hpricot-util.rb", "lib/nokogiri-util.rb", 
    "lib/html-cleaner.rb", "lib/util.rb", "examples/rocketboom.rb", 
    "examples/rocketboom.rss", "test/test_helper.rb"]
  s.homepage = %q{http://wiki.github.com/jdidion/feedme}
  s.rdoc_options = ["--main", "README.txt"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{feedme}
  s.summary = %q{A simple, flexible, and extensible RSS and Atom parser for Ruby}
  s.test_files = ["test/test_helper.rb"]
end
tasks.jeweler.remote = 'github'
Jeweler::GemcutterTasks.new


